collaborators:
  ovv:
    permission: admin
hooks: {}
labels:
  bug:
    color: ee0701
  duplicate:
    color: cccccc
  enhancement:
    color: 84b6eb
  help wanted:
    color: 128A0C
  invalid:
    color: e6e6e6
  question:
    color: cc317c
  wontfix:
    color: ffffff
options:
  allow_merge_commit: true
  allow_rebase_merge: true
  allow_squash_merge: true
  description: Sir-bot-a-lot configuration for pythondev.slack.com
  has_downloads: true
  has_issues: false
  has_wiki: false
  homepage: ''
  name: sirbot-pythondev
  private: false
