collaborators:
  mikefromit:
    permission: admin
  mrasband:
    permission: admin
  ovv:
    permission: admin
  seanson:
    permission: admin
labels:
  bug:
    color: ee0701
  difficulty/easy:
    color: c2e0c6
  difficulty/hard:
    color: e99695
  difficulty/medium:
    color: fef2c0
  difficulty/newcomers:
    color: c5def5
  documentation:
    color: 1d76db
  etc/blocked:
    color: b60205
  etc/duplicate:
    color: cccccc
  etc/invalid:
    color: cccccc
  etc/question:
    color: cccccc
  etc/wontfix:
    color: cccccc
  feature:
    color: d93f0b
  help wanted:
    color: 128A0C
  proposal:
    color: 5319e7
options:
  allow_merge_commit: false
  allow_rebase_merge: true
  allow_squash_merge: true
  description: Sir-bot-a-lot configuration for pythondev.slack.com
  has_downloads: true
  has_issues: true
  has_wiki: false
  homepage: https://pythondev.slack.com
  name: sirbot-pythondev
  private: false