language: python

python:
  - "3.6"

script:
  - python setup.py flake8
  - travis/dothub.sh

deploy:
  provider: script
  script: travis/dothub.sh
  on:
#    repo: pyslackers/sirbot-pythondev
#    branch: master
    python: '3.6'
