sirbot:
  port: 7000
  plugins:
    - sirbot.slack
    - sirbot.plugins.sqlite
    - sirbot.plugins.giphy
    - sirbot.plugins.pypi
    - sirbot.plugins.candy
    - sirbot.plugins.github
    - sirbot.plugins.scheduler
    - pythondev

github:
  endpoint: "/github"

slack:
  priority: 20
  rtm: true
  ping: "robot_face"
  save:
    messages: true
    events: true
    commands: true
    actions: true
  endpoints:
    commands: "/commands"
    actions: "/buttons"
    events: "/events"

sqlite:
  priority: 80
  file: /var/lib/sirbot/sirbot.db

pythondev:
  priority: 1
  candy:
    trigger: ":smile:"
  githhub:
    channel: general
  python_jobs:
    looking: >
        *Weekly who's looking thread !*

        If you are looking for a job please post your resume in this thread.
    looking_tips: >
        We are an international community so please include your location and
        if you are willing to relocate.
    hiring: >
        *Weekly who's hiring thread !*

        If you are looking for someone please post your job in this thread.
    hiring_tips: >
        We are an international community so please include your company
        location and policy on remote employees. A good post should include the
        name of the company, the location, on-site/remote and a quick summary
        of the job.
  digital_ocean:
    url: https://digitalocean.com
    refferral: https://m.do.co/c/457f0988c477
    msg: >
        Here at Python Developers we host our website and Slack bot on
        <{}|Digital Ocean>. If you are planning on using Digital Ocean, please
        use our <{}|referral code>. You get 10 USD, while helping support the
        community by contributing to hosting fees for our site and
        <@sirbotalot>!
  files_template: >
    Click <{}|here> to access the {}.
  files:
    intro_doc:
      name: introduction doc
      match: intro
      url: 'https://github.com/pyslackers/community/blob/master/introduction.md'
    what_next:
      name: what's next doc
      match: what's next
      url: 'https://github.com/pyslackers/community/blob/master/whats_next.md'
  join: >
    Welcome to the community :tada:


    We are glad that you have decided to join us. We have documented a few
    things in the <{}|intro doc> to help you along from the beginning because
    we are grand believers in the Don't Repeat Yourself principle, and it just
    seems so professional!


    May your :taco:s be plentiful!
  moveto:
    msg: >
      Looks like conversation is going off topic. Please move the conversation to <#{}|{}>
    error: >
      NameError: channel name {} does not exist. Please try another channel, or consult the channel listing on Slack to find an appropriate channel.

logging:
  version: 1
  disable_existing_loggers: false
  formatters:
    simple:
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
      stream: ext://sys.stdout
  root:
    level: DEBUG
    handlers: [console]
    propagate: no